### ISSUE TITLE
doesn't support 1.12.2?

### ISSUE THREAD

**Issue by ghost** [KawakawaRitsuki/JapaneCraft#2]
Minecraft 1.12.2 などの新しいバージョンへ対応する予定はありませんか？

**Comment by mizucoffee** [comment]
すみません...今の所ありません...

**Comment by ghost** [comment]
@mizucoffee 
お返事頂きありがとうございます。
なるほど、、、無いのですね・・・。
Forge Server にローマ字を日本語変換自動的にしてくれる機能を追加
できそうなMODが唯一これしか見つからずで、、、、
他にもし同じ機能を提供しているMODをご存知でしたら、教えて頂けると幸いです。

**Comment by mizucoffee** [comment]
Forgeでのサーバー側日本語modは他では見たことないですね...
出来るか分からないですが暇な時に少し試してみようと思います

1.12.2でいいですか？

**Comment by ghost** [comment]
やはりそうですよね、これが唯一無二だと思っています。
もし可能でしたら、アップデートして頂けると大変ありがたいです。
それに、どのようなコード変更を行なえば新しいバージョンに対応できるのか
技術的にも興味があります。勘所つかめば自分でもアップデート出来ないかな、とか
ちょっと思ったりも・・・(^_^;)

1.12.2 で大丈夫です！

**Comment by mizucoffee** [comment]
全然気付いてなかったんですがこのプロジェクトのfork先が対応してるっぽいので一度お試しいただけると良いかもしれません！

https://github.com/wcaokaze/JapaneCraft/releases

**Comment by ghost** [comment]
@mizucoffee 
情報まことにありがとうございます！
試してみたのですが、完璧に動作致しました！
というわけで、このIssueはクローズしますね！
助かりました〜＞＜
